In [1]:
import math
import numpy as np

In [19]:
## 维特比算法，输出最优路径
def viterbi(A, B, PI, O):
    N = A.shape[0]
    I = np.mat(np.zeros((N, 1)))
    T = N
    sigma = np.mat(np.zeros((N, N)))
    omiga = np.mat(np.ones((N, N)))
    index = 0
    
    ## 初始化
    for i in range(N):
        if O[0, 0] == 0:
            index = 0
        else:
            index = 1
        sigma[0, i] = PI[i, 0] * B[i, index]
        
    t = 1
    while t < T:
        for i in range(N):
            sigma_tmp = np.mat(np.zeros((N, 1)))
            for j in range(N):
                sigma_tmp[j, 0] = sigma[t - 1, j] * A[j, i]
            max_value = sigma_tmp.max(axis=0)
            if O[t, 0] == 0:
                index = 0
            else:
                index = 1
            sigma[t, i] = max_value[0, 0] * B[i, index]
            omiga[t, i] = sigma_tmp.argmax() + 1
        t += 1
    I[T - 1, 0] = sigma[N - 1, :].argmax() + 1
    t = T - 2
    print(omiga)
    
    while t >= 0:
        index = int(I[t + 1, 0] - 1)
        I[t, 0] = omiga[t + 1, index]
        t -= 1
            
    return I

In [4]:
## 状态转移概率
A = np.mat([[0.5, 0.2, 0.3],
           [0.3, 0.5, 0.2],
           [0.2, 0.3, 0.5]])

## 发射概率
B = np.mat([[0.5, 0.5],
           [0.4, 0.6],
           [0.7, 0.3]])

## 隐状态的初始概率
PI = np.mat([[0.2],
            [0.4],
            [0.4]])

## 观测状态序列
O = np.mat([[0],
           [1],
           [0]])

In [20]:
I = viterbi(A, B, PI, O)
print(I)

[[1. 1. 1.]
 [3. 3. 3.]
 [2. 2. 3.]]
[[3.]
 [3.]
 [3.]]
