访问、插入、删除、修改ndarray

In [1]:
import numpy as np

In [2]:
x = np.arange(0, 5)
print(x)

[0 1 2 3 4]


In [3]:
## 1维向量与Python中的list基本类似
print("1st element: ", x[0])  # 正索引
print("5th element: ", x[4])
print("1st element: ", x[-5])  # 负索引
print("5th element: ", x[-1])

1st element:  0
5th element:  4
1st element:  0
5th element:  4


In [4]:
## 修改ndarray中的元素
x[3] = 20
print(x)

[ 0  1  2 20  4]


In [5]:
## 2维向量
x = np.arange(0, 10).reshape(5, 2)
print(x)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [8]:
print("Element at (0, 0):  ", x[0, 0])
print("Element at (0, 1):  ", x[0, 1])
print("Element at (1, 1):  ", x[1, 1])
# print("Element at (1, 3):  ", x[1, 3])  # IndexError

Element at (0, 0):   0
Element at (0, 1):   1
Element at (1, 1):   3


IndexError: index 3 is out of bounds for axis 1 with size 2

In [9]:
x[0, 0] = 20
print(x)

[[20  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]]


删除ndarray中的元素

In [11]:
## 一维向量
y = np.arange(0, 10)
print(y)

y = np.delete(y, 0)  # 删除第1个元素 
print(y)

y = np.delete(y, [0, 3])  # 删除第1个和第3个元素
print(y)

[0 1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[2 3 5 6 7 8 9]


In [15]:
## 二维向量
y = np.arange(1, 10).reshape((3, 3))
print(y)

y = np.delete(y, 0)  # 删除第1个元素，会将y变成一维向量
print(y)

y = np.arange(1, 10).reshape((3, 3))
y = np.delete(y, 0, axis=0)  # axis=0代表删除行， 0表示删除第1行
print(y)

y = np.delete(y, [0, 1], axis=1)  # axis=1代表删除列，[0, 1]代表删除第1列和第2列
print(y)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[2 3 4 5 6 7 8 9]
[[4 5 6]
 [7 8 9]]
[[6]
 [9]]


In [34]:
## 多维矩阵
z = np.arange(1, 28).reshape((3, 3, 3))
print(z)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


In [35]:
print("Element at (0, 0, 0):", z[0, 0, 0])
print("Element at (1, 1, 1):", z[1, 1, 1])
print(z[0])
print(z[0, 0])

Element at (0, 0, 0): 1
Element at (1, 1, 1): 14
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3]


In [36]:
z = np.delete(z, [0, 1], axis=0)
print(z)

[[[19 20 21]
  [22 23 24]
  [25 26 27]]]


In [38]:
z = np.arange(1, 28).reshape((3, 3, 3))
z = np.delete(z, [0, 1], axis=1)
print(z)

[[[ 7  8  9]]

 [[16 17 18]]

 [[25 26 27]]]


In [39]:
z = np.arange(1, 28).reshape((3, 3, 3))
z = np.delete(z, [0, 1], axis=2)
print(z)

[[[ 3]
  [ 6]
  [ 9]]

 [[12]
  [15]
  [18]]

 [[21]
  [24]
  [27]]]


插入元素

In [42]:
## 一维数组，与list类似
x = np.arange(1, 6)
print(x)

x = np.append(x, 6)
print(x)

x = np.append(x, [7, 8])
print(x)

[1 2 3 4 5]
[1 2 3 4 5 6]
[1 2 3 4 5 6 7 8]


In [43]:
## 二维数组
y = np.arange(1, 10).reshape((3, 3))
print(y)

y = np.append(y, 10)  # 会将y转变为一维数组
print(y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[ 1  2  3  4  5  6  7  8  9 10]


In [50]:
y = np.arange(1, 10).reshape((3, 3))
y = np.append(y, [[10, 11, 12]], axis=0)  # 插入一行，插入的数据必须与匹配原始矩阵的列数
print(y)
print(np.array([[10, 11, 12]]).shape)  # 1行3列

y = np.append(y, [[1, 1, 1], [2, 2, 2]], axis=0)  # 插入二行
print(y)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(1, 3)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [ 1  1  1]
 [ 2  2  2]]


In [51]:
y = np.arange(1, 10).reshape((3, 3))
y = np.append(y, [[10], [11], [12]], axis=1)  # 插入一列
print(y)

[[ 1  2  3 10]
 [ 4  5  6 11]
 [ 7  8  9 12]]


In [52]:
y = np.append(y, [[1, 2], [1, 2], [1, 2]], axis=1)  # 插入二列
print(y)

[[ 1  2  3 10  1  2]
 [ 4  5  6 11  1  2]
 [ 7  8  9 12  1  2]]


插入指定的位置

In [57]:
## 一维数组
x = np.array([10, 20, 50, 60])
print(x)

x = np.insert(x, 2, [3, 4])  # 2代表索引为2的位置
print(x)

[10 20 50 60]
[10 20  3  4 50 60]


In [63]:
## 二维数组
y = np.arange(1, 10).reshape((3, 3))
print(y)

y = np.insert(y, 1, [10, 10, 10], axis=0)  # 插入1行，行索引为1， 与append有所不同
print(y)

y = np.insert(y, 2, [[100, 100, 100], [1000, 1000, 1000]], axis=0)  # 插入两行
print(y)

y = np.insert(y, 1, [2, 2, 2, 2, 2, 2], axis=1)  # 插入1列
print(y)

y = np.insert(y, 2, 99, axis=1)  # 插入1列全部数据为99
print(y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  2  3]
 [10 10 10]
 [ 4  5  6]
 [ 7  8  9]]
[[   1    2    3]
 [  10   10   10]
 [ 100  100  100]
 [1000 1000 1000]
 [   4    5    6]
 [   7    8    9]]
[[   1    2    2    3]
 [  10    2   10   10]
 [ 100    2  100  100]
 [1000    2 1000 1000]
 [   4    2    5    6]
 [   7    2    8    9]]
[[   1    2   99    2    3]
 [  10    2   99   10   10]
 [ 100    2   99  100  100]
 [1000    2   99 1000 1000]
 [   4    2   99    5    6]
 [   7    2   99    8    9]]


NumPy中矩阵的组合

In [74]:
## 垂直组合
x = np.array([1, 2])
print(x)  # 1行2列

y = np.array([[3, 4], [5, 6]])
print(y)

z = np.vstack((x, y))  # 
print(z)

## 水平组合
w = np.hstack((x.reshape((2, 1)), y))  # 需要将x转变为2行1列的矩阵
print(w)

[1 2]
[[3 4]
 [5 6]]
[[1 2]
 [3 4]
 [5 6]]
[[1 3 4]
 [2 5 6]]
