ndarray的切片

In [1]:
import numpy as np

In [2]:
X = np.arange(1, 21).reshape((4, 5))
print(X)

z = X[1:4, 2:5]  # 1-3行，2-4列
print(z)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[ 8  9 10]
 [13 14 15]
 [18 19 20]]


In [3]:
z = X[:3, 2:]  # 前3行，3-最后1列
print(z)

[[ 3  4  5]
 [ 8  9 10]
 [13 14 15]]


In [5]:
z = X[:, 2]  # 第3列
print(z)

[ 3  8 13 18]


In [6]:
z = X[2, :]  # 第3行
print(z)

[11 12 13 14 15]


In [7]:
z = X[2:3, :]  # 返回一个二维矩阵
print(z)

[[11 12 13 14 15]]


In [13]:
c = X[2, :]
print(c)

c[-1] = 555  # 修改最后c的最后一个元素，同样会引起X的元素变化，c引用的是X第3行的对象
print(X)

[ 11  12  13  14 555]
[[  1   2   3   4   5]
 [  6   7   8   9  10]
 [ 11  12  13  14 555]
 [ 16  17  18  19  20]]


In [11]:
## 如果希望避免这种情况
c = X[2, :].copy()  # 创建新的ndarray
print(c)

c[-1] = 666
print(c)
print()
print(X)

[ 11  12  13  14 555]
[ 11  12  13  14 666]

[[  1   2   3   4   5]
 [  6   7   8   9  10]
 [ 11  12  13  14 555]
 [ 16  17  18  19  20]]


In [17]:
## 使用ndarray对另一个ndarray进行切片
indices = np.array([1, 3])
X = np.arange(1, 21).reshape((4, 5))
print(X)
print()

y = X[indices, :]  # 第2行和第4行
print(y)

y = X[:, indices]  # 第2列和第4列
print(y)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

[[ 6  7  8  9 10]
 [16 17 18 19 20]]
[[ 2  4]
 [ 7  9]
 [12 14]
 [17 19]]


In [16]:
## 提取对角线元素
z = np.diag(X)  # 主对角线
print(z)

[ 1  7 13 19]


In [18]:
z = np.diag(X, k=1)  # 主对角线上方第1条对角线元素
print(z)

[ 2  8 14 20]


In [19]:
z = np.diag(X, k=2)  # 主对角线上方第2条对角线元素
print(z)

[ 3  9 15]


In [20]:
z = np.diag(X, k=-1)  # 主对角线下方第1条对角线元素
print(z)

[ 6 12 18]


In [21]:
X = np.array([[1, 2, 3], [5, 2, 8], [1, 2, 3]])
print(np.unique(X))  # 独一无二的元素

[1 2 3 5 8]
