算术运算和广播

In [1]:
import numpy as np

参考：https://www.cnblogs.com/jiaxin359/p/9021726.html
https://blog.csdn.net/zk_j1994/article/details/72589014
NumPy中算术运算的函数要求输入的数组shape必须一致，如果不一致就需要使用广播机制，也就是说如果多个数组希望使用算术运算，则最低要求是可广播，否则就会出错。
广播的要求：
1. 让所有输入数组都向其中shape最长的数组看齐，shape中不足的部分都通过在前面加1补齐
2. 输出数组的shape是输入数组shape的各个轴上的最大值
3. 如果输入数组的某个轴和输出数组的对应轴的长度相同或者其长度为1时，这个数组能够用来计算，否则出错
4. 当输入数组的某个轴的长度为1时，沿着此轴运算时都用此轴上的第一组值

In [2]:
## 一维数组的元素运算（与线性代数的矩阵运算不同）
#
x = np.array([1, 2, 3, 4])
y = np.array([5, 6, 7, 8])
# y = np.array([5, 6, 7, 8, 9])  # error，不满足条件3
print('x = ',x)
print()
print('y = ', y)
print()

x =  [1 2 3 4]

y =  [5 6 7 8]



In [3]:
print("x + y: ", x + y)
print("add(x, y): ", np.add(x, y))

x + y:  [ 6  8 10 12]
add(x, y):  [ 6  8 10 12]


In [4]:
print("x - y: ", x - y)
print("subtract(x, y): ", np.subtract(x, y))

x - y:  [-4 -4 -4 -4]
subtract(x, y):  [-4 -4 -4 -4]


In [5]:
print("x * y: ", x * y)
print("multiply(x, y): ", np.multiply(x, y))

x * y:  [ 5 12 21 32]
multiply(x, y):  [ 5 12 21 32]


In [26]:
print("x: ", x)
print("y: ", y)
print("x dot y: ", np.dot(x, y))  # np.sum(x * y)

x:  [-1  2  3  4]
y:  [5 6 7 8]
x dot y:  60


In [6]:
print("x / y: ", x / y)
print("divide(x, y): ", np.divide(x, y))

x / y:  [0.2        0.33333333 0.42857143 0.5       ]
divide(x, y):  [0.2        0.33333333 0.42857143 0.5       ]


二维数组的广播：
A: (2, 3)
B: (3,)
A + B：按照规则1，B的shape广播成(1, 3)，按照规则2，结果result为(2, 3)，A,B的列长度都与result相同，A的行长度与result相同，B的不同但为1，可以运算，OK

A: (2, 3)
B: (4, )
A + B: 按照规则2，结果result为(2, 4)，A的列长度与result不同，不能运算，Error

In [7]:
A = np.arange(1, 7).reshape((2, 3))
B = np.ones(3, dtype=int)

print("A = ", A)
print("A.shape: ", A.shape)
print()
print("B = ", B)
print("B.shape: ", B.shape)

A =  [[1 2 3]
 [4 5 6]]
A.shape:  (2, 3)

B =  [1 1 1]
B.shape:  (3,)


In [8]:
print("A + B: ", A + B)

A + B:  [[2 3 4]
 [5 6 7]]


In [9]:
B1 = np.ones(4, dtype=int)
# print(A + B1)  # Error

In [10]:
# A: (6, 1) B: (5,)
A = np.arange(1, 7).reshape((6, 1))
B = np.zeros((1, 6), dtype=int)

print("A: ", A)
print("B:", B)
print()

# A + B : (6, 5)
# 应用规则4：A中每一行的元素都与B的第1行元素相加
print("A + B: ", A + B)

A:  [[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
B: [[0 0 0 0 0 0]]

A + B:  [[1 1 1 1 1 1]
 [2 2 2 2 2 2]
 [3 3 3 3 3 3]
 [4 4 4 4 4 4]
 [5 5 5 5 5 5]
 [6 6 6 6 6 6]]


In [11]:
# A:(6, 1) 
# 标量的shape为()，所以输出结果的shape为(6, 1)
print("A + 5: ", A + 5)

A + 5:  [[ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]]


多维多个数组元素运算：
A：(2, 3, 3)
B: (3, 3)
C: (3,)
D: 5

In [12]:
A = np.arange(1, 19).reshape((2, 3, 3))
B = np.arange(1, 10).reshape((3, 3))
C = np.array([9, 9, 9])
D = 5

# result: (2, 3, 3)
result = A + B + C + D
print("A + B + C + D: ", result)
print(result.shape)

A + B + C + D:  [[[16 18 20]
  [22 24 26]
  [28 30 32]]

 [[25 27 29]
  [31 33 35]
  [37 39 41]]]
(2, 3, 3)


对ndarray的数组元素应用数学函数

In [13]:
x = np.array([1, 2, 3, 4])

print("x: ", x)

x:  [1 2 3 4]


In [14]:
print("sqrt(x): ", np.sqrt(x))

sqrt(x):  [1.         1.41421356 1.73205081 2.        ]


In [15]:
print("exp(x): ", np.exp(x))

exp(x):  [ 2.71828183  7.3890561  20.08553692 54.59815003]


In [16]:
print("power(x, 2): ", np.power(x, 2))

power(x, 2):  [ 1  4  9 16]


In [17]:
## 非0元素的个数
np.nonzero(x)[0].size

4

In [18]:
x[0] = -1
x

array([-1,  2,  3,  4])

In [19]:
## 绝对值
np.abs(x)

array([1, 2, 3, 4])

NumPy中的统计学函数

In [20]:
X = np.array([[1, 2], [3, 4]])

print("X = ", X)
print()

X =  [[1 2]
 [3 4]]



In [21]:
print("Average of all elements in X: ", X.mean())

# axis=0表示按行计算平均值，把每行同一位置的元素相加求平均值
print("Average of all elements in the columns of X: ", X.mean(axis=0))
print("Average of all elements in the rows of X: ", X.mean(axis=1))

Average of all elements in X:  2.5
Average of all elements in the columns of X:  [2. 3.]
Average of all elements in the rows of X:  [1.5 3.5]


In [22]:
# 标准差
print("Standard Deviation of all elements in X: ", X.std())
print("Standard Deviation of all elements in the columns of X: ", X.std(axis=0))
print("Standard Deviation of all elements in the rows of X: ", X.std(axis=1))

Standard Deviation of all elements in X:  1.118033988749895
Standard Deviation of all elements in the columns of X:  [1. 1.]
Standard Deviation of all elements in the rows of X:  [0.5 0.5]


In [23]:
# 中位数：偶数个取最中间两数的平均值，奇数个取排序后的中间值
print("Median of all elements in X: ", np.median(X))
print("Median of all elements in the columns of X: ", np.median(X, axis=0))
print("Median of all elements in the rows of X: ", np.median(X, axis=1))

Median of all elements in X:  2.5
Median of all elements in the columns of X:  [2. 3.]
Median of all elements in the rows of X:  [1.5 3.5]
