In [1]:
import numpy as np

布尔型索引，集合与排序

In [5]:
X = np.random.randint(1, 1000, (10, 10))
print(X)

[[220 665 369 445 140 698 162 699 716 686]
 [165  36 193 771 462 757 114 157 454 551]
 [144 557 384 133 305 307 794 542 445 561]
 [311 795 725 166  86 684  78   7 684   9]
 [908 562 416 682 602 351  80 523 247 895]
 [559  86 919 790 550 892  68 449 578 653]
 [937 247 919 827  38 751 639 868  68 261]
 [594 493 117 743 179 150 350 227  69 236]
 [248 119 569  49 603 404 337 669 680 795]
 [494 709 231 200 156 444 351 325 434 631]]


In [6]:
max_200 = X[X > 200]  # 所有大于200的元素
print(max_200)

[220 665 369 445 698 699 716 686 771 462 757 454 551 557 384 305 307 794
 542 445 561 311 795 725 684 684 908 562 416 682 602 351 523 247 895 559
 919 790 550 892 449 578 653 937 247 919 827 751 639 868 261 594 493 743
 350 227 236 248 569 603 404 337 669 680 795 494 709 231 444 351 325 434
 631]


In [7]:
min_200 = X[X <= 200]  # 所有小于等于200的元素
print(min_200)

[140 162 165  36 193 114 157 144 133 166  86  78   7   9  80  86  68  38
  68 117 179 150  69 119  49 200 156]


In [9]:
y = X[(X >= 100) & (X < 200)]  # 大于等于100并且小于200，两个条件判断的()不能省略
print(y)

[140 162 165 193 114 157 144 133 166 117 179 150 119 156]


In [10]:
## 通过布尔型索引进行元素修改
X[(X >= 100) & (X < 200)] = -1
print(X)

[[220 665 369 445  -1 698  -1 699 716 686]
 [ -1  36  -1 771 462 757  -1  -1 454 551]
 [ -1 557 384  -1 305 307 794 542 445 561]
 [311 795 725  -1  86 684  78   7 684   9]
 [908 562 416 682 602 351  80 523 247 895]
 [559  86 919 790 550 892  68 449 578 653]
 [937 247 919 827  38 751 639 868  68 261]
 [594 493  -1 743  -1  -1 350 227  69 236]
 [248  -1 569  49 603 404 337 669 680 795]
 [494 709 231 200  -1 444 351 325 434 631]]


高级布尔型索引

In [2]:
names = np.array(["Bob", "Joe", "Jhon", "Will", "Tom", "Joe"])
data = np.random.randint(1, 100, (6, 4))
print(data)

[[19 40 32 28]
 [55 62 75 30]
 [26  3 98 96]
 [ 3 85 70 14]
 [66 80 12 35]
 [29 61 85  3]]


In [5]:
Joe_name = names == "Joe"
print(Joe_name)

[False  True False False False  True]


In [6]:
data[Joe_name]

array([[55, 62, 75, 30],
       [29, 61, 85,  3]])

In [8]:
data[~Joe_name]  # 除了Joe_name之外的元素

array([[19, 40, 32, 28],
       [26,  3, 98, 96],
       [ 3, 85, 70, 14],
       [66, 80, 12, 35]])

In [9]:
mask = (names == 'Joe') | (names == 'Bob')
mask

array([ True,  True, False, False, False,  True], dtype=bool)

ndarray的集合运算

In [12]:
## 一维数组
x = np.array([1, 2, 3, 4, 5])
y = np.array([1, 2, 3, 7, 8])

print(np.intersect1d(x, y))  # 交集
print(np.union1d(x, y))  # 并集
print(np.setdiff1d(x, y))  # x中有，y中没有
print(np.setdiff1d(y, x))  # y中有，x中没有

[1 2 3]
[1 2 3 4 5 7 8]
[4 5]
[7 8]


In [15]:
## 二维数组
x = np.arange(1, 9).reshape((4, 2))
y = np.arange(2, 10).reshape((2, 4))
print(x)
print()
print(y)
print()

# 如果输入参数不是一维，则转为一维数组
print(np.intersect1d(x, y))  # 交集
print(np.union1d(x, y))  # 并集
print(np.setdiff1d(x, y))  # x中有，y中没有
print(np.setdiff1d(y, x))  # y中有，x中没有

[[1 2]
 [3 4]
 [5 6]
 [7 8]]

[[2 3 4 5]
 [6 7 8 9]]

[2 3 4 5 6 7 8]
[1 2 3 4 5 6 7 8 9]
[1]
[9]


排序

In [18]:
## 一维数组
x = np.random.randint(1, 11, size=(10,))
print(x)

[6 4 9 5 4 2 5 4 6 7]


In [21]:
## 不修改元素数组
print(np.sort(x))
print(x)

[2 4 4 4 5 5 6 6 7 9]
[2 4 4 4 5 5 6 6 7 9]


In [23]:
## 修改元素数组
x.sort()
print(x)

[2 4 4 4 5 5 6 6 7 9]


In [30]:
## 二维数组
x = np.random.randint(1, 11, size=(5, 3))
print(x)
print()

print(np.sort(x, axis=0))  # 按行排序，每一列的元素沿着行的方向递增
print()

print(np.sort(x, axis=1)) # 按列排序，每一行的元素沿着列的方向递增
print()

print(np.sort(x))  # 默认按照最后一个维度排序，与按列排序一致
print()

print(np.sort(x, None))  # 将x拉平（转变为一维数组）然后进行排序

[[10  8  8]
 [ 2  7  1]
 [10  9  7]
 [ 8  1  4]
 [ 2  3  8]]

[[ 2  1  1]
 [ 2  3  4]
 [ 8  7  7]
 [10  8  8]
 [10  9  8]]

[[ 8  8 10]
 [ 1  2  7]
 [ 7  9 10]
 [ 1  4  8]
 [ 2  3  8]]

[[ 8  8 10]
 [ 1  2  7]
 [ 7  9 10]
 [ 1  4  8]
 [ 2  3  8]]

[ 1  1  2  2  3  4  7  7  8  8  8  8  9 10 10]
