## 训练神经网络

In [2]:
import numpy as np
import time

import torch
from torch import nn
from torch import optim
import torch.nn.functional as F
from torch.autograd import Variable

import helper

## Autograd计算梯度

In [3]:
x = torch.randn(2, 2)  # 正态分布的随机数
x

tensor([[-1.1637,  0.5200],
        [-0.1843, -0.4492]])

In [4]:
## 使用torch.autograd中的Variable封装张量，并且指明需要梯度
x = Variable(x, requires_grad=True)
x

tensor([[-1.1637,  0.5200],
        [-0.1843, -0.4492]], requires_grad=True)

In [5]:
# grad_fn看出执行了Pow运算
y = x ** 2
y

tensor([[1.3542, 0.2704],
        [0.0340, 0.2018]], grad_fn=<PowBackward0>)

In [6]:
# x的梯度为空
x.grad

In [7]:
# 标量才能隐式创建梯度
# y.backward()

RuntimeError: grad can be implicitly created only for scalar outputs

In [8]:
z = y.mean()
z

tensor(0.4651, grad_fn=<MeanBackward1>)

要计算梯度，你需要对 Variable（例如 `z`）运行 `.backward` 方法。这样会计算 `z` 相对于 `x` 的梯度

$$
\frac{\partial z}{\partial x} = \frac{\partial}{\partial x}\left[\frac{1}{n}\sum_i^n x_i^2\right] = \frac{x}{2}
$$

In [9]:
z.backward()

In [10]:
# x.grad确实是x / 2
x.grad

tensor([[-0.5818,  0.2600],
        [-0.0921, -0.2246]])