Pytorch学习：张量Tensor

In [1]:
import numpy as np
import torch

In [2]:
## 随机张量
## 矩阵是二维张量，向量是一维张量
x = torch.rand(3, 2)
x

tensor([[0.5830, 0.1463],
        [0.3856, 0.8141],
        [0.4950, 0.2826]])

In [3]:
x.shape

torch.Size([3, 2])

In [4]:
x.size()  # 与numpy不太相同

torch.Size([3, 2])

In [5]:
y = torch.ones(x.size())
y

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [6]:
z = x + y
z

tensor([[1.5830, 1.1463],
        [1.3856, 1.8141],
        [1.4950, 1.2826]])

In [7]:
## 索引访问
## 第1行
z[0]

tensor([1.5830, 1.1463])

In [8]:
## 第1列
z[:, 0]

tensor([1.5830, 1.3856, 1.4950])

In [9]:
z[0, 0]

tensor(1.5830)

In [10]:
## 加法
## 产生新的张量
z.add(1)

tensor([[2.5830, 2.1463],
        [2.3856, 2.8141],
        [2.4950, 2.2826]])

In [11]:
z

tensor([[1.5830, 1.1463],
        [1.3856, 1.8141],
        [1.4950, 1.2826]])

In [12]:
## 原地修改，函数名多了一个下划线
z.add_(1)

tensor([[2.5830, 2.1463],
        [2.3856, 2.8141],
        [2.4950, 2.2826]])

In [13]:
z

tensor([[2.5830, 2.1463],
        [2.3856, 2.8141],
        [2.4950, 2.2826]])

修改张量形状

In [14]:
z.reshape(2, 3)  ## 3x2转变为2x3

tensor([[2.5830, 2.1463, 2.3856],
        [2.8141, 2.4950, 2.2826]])

In [15]:
z

tensor([[2.5830, 2.1463],
        [2.3856, 2.8141],
        [2.4950, 2.2826]])

In [16]:
z.resize_(2, 3)  ## 原地修改

tensor([[2.5830, 2.1463, 2.3856],
        [2.8141, 2.4950, 2.2826]])

In [17]:
z

tensor([[2.5830, 2.1463, 2.3856],
        [2.8141, 2.4950, 2.2826]])

Numpy与Torch相互转换

In [18]:
## Numpy to Torch
a = np.random.rand(4, 3)
a

array([[0.3567908 , 0.7439755 , 0.2064541 ],
       [0.52145119, 0.58751519, 0.49045748],
       [0.82201819, 0.61613166, 0.93497149],
       [0.28809986, 0.77159753, 0.95400818]])

In [19]:
b = torch.from_numpy(a)
b

tensor([[0.3568, 0.7440, 0.2065],
        [0.5215, 0.5875, 0.4905],
        [0.8220, 0.6161, 0.9350],
        [0.2881, 0.7716, 0.9540]], dtype=torch.float64)

In [20]:
## 内存会在Numpy和Torch之间共享，修改一个，也会改变另一个
b.mul_(2)  ## 原地修改
b

tensor([[0.7136, 1.4880, 0.4129],
        [1.0429, 1.1750, 0.9809],
        [1.6440, 1.2323, 1.8699],
        [0.5762, 1.5432, 1.9080]], dtype=torch.float64)

In [21]:
a  ## 可以看出a同样发生了改变

array([[0.71358159, 1.487951  , 0.41290819],
       [1.04290239, 1.17503038, 0.98091497],
       [1.64403638, 1.23226331, 1.86994297],
       [0.57619972, 1.54319506, 1.90801636]])

In [22]:
a[0, 0] = 1000

In [23]:
a

array([[1.00000000e+03, 1.48795100e+00, 4.12908192e-01],
       [1.04290239e+00, 1.17503038e+00, 9.80914966e-01],
       [1.64403638e+00, 1.23226331e+00, 1.86994297e+00],
       [5.76199723e-01, 1.54319506e+00, 1.90801636e+00]])

In [24]:
b  ## 原地修改a，则b也发生变化

tensor([[1.0000e+03, 1.4880e+00, 4.1291e-01],
        [1.0429e+00, 1.1750e+00, 9.8091e-01],
        [1.6440e+00, 1.2323e+00, 1.8699e+00],
        [5.7620e-01, 1.5432e+00, 1.9080e+00]], dtype=torch.float64)

### 但如果不是${\color{red}{原地修改}}$，则不会出现这种情况
### 下面这种修改方式就不会

In [25]:
a = np.add(a, 1)
a

array([[1001.        ,    2.487951  ,    1.41290819],
       [   2.04290239,    2.17503038,    1.98091497],
       [   2.64403638,    2.23226331,    2.86994297],
       [   1.57619972,    2.54319506,    2.90801636]])

In [26]:
b  ## b未发生改变

tensor([[1.0000e+03, 1.4880e+00, 4.1291e-01],
        [1.0429e+00, 1.1750e+00, 9.8091e-01],
        [1.6440e+00, 1.2323e+00, 1.8699e+00],
        [5.7620e-01, 1.5432e+00, 1.9080e+00]], dtype=torch.float64)

In [27]:
## Torch to Numpy
c = torch.rand(2, 2)
c

tensor([[0.3966, 0.2504],
        [0.6946, 0.9037]])

In [28]:
d = c.numpy()
d

array([[0.39664626, 0.25043172],
       [0.69456506, 0.9036878 ]], dtype=float32)

In [29]:
c.add_(2)
c

tensor([[2.3966, 2.2504],
        [2.6946, 2.9037]])

In [30]:
d  ## d也会跟着改变

array([[2.3966463, 2.2504318],
       [2.694565 , 2.9036877]], dtype=float32)

In [31]:
d[0, 0] = 100
d

array([[100.       ,   2.2504318],
       [  2.694565 ,   2.9036877]], dtype=float32)

In [32]:
c  ## c也会跟着改变

tensor([[100.0000,   2.2504],
        [  2.6946,   2.9037]])

In [33]:
x = c.cuda()
x

tensor([[100.0000,   2.2504],
        [  2.6946,   2.9037]], device='cuda:0')